name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --quiet --all-targets
    - name: Build with Tokio support
      run: cargo build --quiet --features tokio --all-targets
